export const LOGIN = "LOGIN";
export const SET_ROLE = "SET_ROLE";
export const SET_MENULIST = "SET_MENULIST";
export const SET_ROLELIST = "SET_ROLELIST";
export const SET_USERINFOLIST = "SET_USERINFOLIST";
export const SHOW_USERINFO = "SHOW_USERINFO";
export const UPDATE_USER = "UPDATE_USER"; //登录时修改state
export const UPDATE_USERINFO = "UPDATE_USERINFO";
export const CREATE_TEACHER = "CREATE_TEACHER";
export const DELETE_USERINFO = "DELETE_USERINFO";
export const CREATE_LAB = "CREATE_LAB";
export const UPDATE_LABLIST = "UPDATE_LABLIST";
export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_COURSELIST = "UPDATE_COURSELIST";
export const UPDATE_ORDEREDLIST = "UPDATE_ORDEREDLIST"; //SCHEDULE--ORDEREDINFO
export const UPDATE_lABORDERLIST = "UPDATE_lABORDERLIST"; //预约数据表——laborderinfolist
export const UPDATE_COURSELISTLAB = "UPDATE_COURSELISTLAB"; //课程信息列表的lab属性——courseinfolist
export const UPDATE_LABOCCUPY = "UPDATE_LABOCCUPY";
